[package]
name = "mirtrs"
version = "0.1.0"
authors = ["mvlabat <mvlabat@gmail.com>"]
edition = "2018"

[dependencies]
dotenv = "0.14.1"
futures = "0.1.28"
telegram-bot = "0.6.3"
tokio-core = "0.1.17"
